defaults:
  - /model/eomt/base@_here_

model:
  backbone:
    _target_: aidall_seg.models.backbones.PlainViTBackbone
    backbone_name: vit_large_patch14_reg4_dinov2
    img_size: 518
    l2_blocks: 4
